[project]
name = "upsonic-ai-django-case"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=5.2.8",
    "redis>=7.1.0",
]
